category:  reverse
points:    400
title:     Minimum system requirements
author:    Rozetkin
description: >
    <p>Ох, я не уверен, что ваш компьютер потянет этот высокотехнологичный лабиринт. В любом случае вы можете попробовать.</p>
    <p><em>Добавлено в 15:10:</em></p>
    <p>
      <b>Обновление.</b> Исполняемый файл обновлен без изменения логики.
    </p>
    <p>
      <b>Подсказка.</b> Говорят, что вам может помочь одна женщина по имени Ида. Хоть обычно она и
      помогает за большую сумму, но иногда она и бесплатно помочь может.
    </p>
generator: kyzylborda-docker-generator Dockerfile.generator ./generator.py
daemon:
  exec: kyzylborda-docker-compose-daemon
  cwd: app
  socket: ./app.sock
  socket_type: http
